[tool.poetry]
name = "kanerfs"
version = "0.1.0"
description = "NeRFs implementation using KANs"
authors = ["Meghana"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
